# Continuous Integration
name: CI

on:
  pull_request:
    branches: [ master, develop ]

jobs:

  test-backend:
    name: Test backend
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_DEV }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY_DEV }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION_DEV }}
      AWS_S3_PWA_BUCKET: ${{ secrets.AWS_S3_PWA_BUCKET_DEV }}

    steps:
      - uses: actions/checkout@v2

      - name: Instalar AWS CLI 2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      - name: Pruebas AWS Lambda
        run: |
          aws --version
          sam --version
          cd backend/aws
          chmod +x testing.sh
          ./testing.sh

  test-frontend:
    name: Test frontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Pruebas PWA
        run: |
          cd frontend
          chmod +x testing.sh
          ./testing.sh